diff --git a/Makefile b/Makefile
index 120661f..9c5c293 100644
--- a/Makefile
+++ b/Makefile
@@ -1,7 +1,7 @@
 VERSION = 1
 PATCHLEVEL = 34
 SUBLEVEL = 0
-EXTRAVERSION =
+EXTRAVERSION = -jzinferno
 NAME = Unnamed
 
 # *DOCUMENTATION*
@@ -288,15 +288,15 @@ MAKEFLAGS += -rR
 
 # Make variables (CC, etc...)
 
-AS		= $(CROSS_COMPILE)as
-CC		= $(CROSS_COMPILE)gcc
+AS		= llvm-as
+CC		= clang
 LD		= $(CC) -nostdlib
 CPP		= $(CC) -E
-AR		= $(CROSS_COMPILE)ar
-NM		= $(CROSS_COMPILE)nm
-STRIP		= $(CROSS_COMPILE)strip
-OBJCOPY		= $(CROSS_COMPILE)objcopy
-OBJDUMP		= $(CROSS_COMPILE)objdump
+AR		= llvm-ar
+NM		= llvm-nm
+STRIP		= llvm-strip
+OBJCOPY		= llvm-objcopy
+OBJDUMP		= llvm-objdump
 PKG_CONFIG	?= $(CROSS_COMPILE)pkg-config
 AWK		= awk
 GENKSYMS	= scripts/genksyms/genksyms
diff --git a/Makefile.flags b/Makefile.flags
index 6674819..84eadde 100644
--- a/Makefile.flags
+++ b/Makefile.flags
@@ -17,17 +17,17 @@ CPPFLAGS += \
 	$(if $(CONFIG_LFS),-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64) \
 	-DBB_VER=$(squote)$(quote)$(BB_VER)$(quote)$(squote)
 
-CFLAGS += $(call cc-option,-Wall,)
-CFLAGS += $(call cc-option,-Wshadow,)
-CFLAGS += $(call cc-option,-Wwrite-strings,)
-CFLAGS += $(call cc-option,-Wundef,)
-CFLAGS += $(call cc-option,-Wstrict-prototypes,)
-CFLAGS += $(call cc-option,-Wunused -Wunused-parameter,)
-CFLAGS += $(call cc-option,-Wunused-function -Wunused-value,)
-CFLAGS += $(call cc-option,-Wmissing-prototypes -Wmissing-declarations,)
-CFLAGS += $(call cc-option,-Wno-format-security,)
+# CFLAGS += $(call cc-option,-Wall,)
+# CFLAGS += $(call cc-option,-Wshadow,)
+# CFLAGS += $(call cc-option,-Wwrite-strings,)
+# CFLAGS += $(call cc-option,-Wundef,)
+# CFLAGS += $(call cc-option,-Wstrict-prototypes,)
+# CFLAGS += $(call cc-option,-Wunused -Wunused-parameter,)
+# CFLAGS += $(call cc-option,-Wunused-function -Wunused-value,)
+# CFLAGS += $(call cc-option,-Wmissing-prototypes -Wmissing-declarations,)
+# CFLAGS += $(call cc-option,-Wno-format-security,)
 # warn about C99 declaration after statement
-CFLAGS += $(call cc-option,-Wdeclaration-after-statement,)
+# CFLAGS += $(call cc-option,-Wdeclaration-after-statement,)
 # If you want to add more -Wsomething above, make sure that it is
 # still possible to build bbox without warnings.
 
@@ -45,11 +45,11 @@ CFLAGS += $(call cc-option,-Werror,)
 #CFLAGS += $(call cc-ifversion, -eq, 0404, -fno-strict-aliasing)
 endif
 # gcc 3.x emits bogus "old style proto" warning on find.c:alloc_action()
-CFLAGS += $(call cc-ifversion, -ge, 0400, -Wold-style-definition)
+CFLAGS += $(call cc-ifversion, -ge, 0400, -w)
 
 ifneq ($(CC),clang)
 # "clang-9: warning: optimization flag '-finline-limit=0' is not supported
-CFLAGS += $(call cc-option,-finline-limit=0,)
+# CFLAGS += $(call cc-option,-finline-limit=0,)
 endif
 
 CFLAGS += $(call cc-option,-fno-builtin-strlen -fomit-frame-pointer -ffunction-sections -fdata-sections,)
@@ -64,10 +64,10 @@ ifeq ($(CONFIG_STATIC_LIBGCC),y)
 CFLAGS += $(call cc-option,-static-libgcc,)
 endif
 
-CFLAGS += $(call cc-option,-falign-functions=1,)
+# CFLAGS += $(call cc-option,-falign-functions=1,)
 ifneq ($(CC),clang)
 # "clang-9: warning: optimization flag '-falign-jumps=1' is not supported" (and same for other two)
-CFLAGS += $(call cc-option,-falign-jumps=1 -falign-labels=1 -falign-loops=1,)
+# CFLAGS += $(call cc-option,-falign-jumps=1 -falign-labels=1 -falign-loops=1,)
 endif
 
 # Defeat .eh_frame bloat (gcc 4.6.3 x86-32 defconfig: 20% smaller busybox binary):
@@ -78,16 +78,16 @@ CFLAGS += $(call cc-option,-fno-asynchronous-unwind-tables,)
 CFLAGS += $(call cc-option,-fno-builtin-printf,)
 
 # clang-9 does not like "str" + N and "if (CONFIG_ITEM && cond)" constructs
-ifeq ($(CC),clang)
+# ifeq ($(CC),clang)
 CFLAGS += $(call cc-option,-Wno-string-plus-int -Wno-constant-logical-operand)
-endif
+# endif
 
 # FIXME: These warnings are at least partially to be concerned about and should
 # be fixed..
 #CFLAGS += $(call cc-option,-Wconversion,)
 
 ifneq ($(CONFIG_DEBUG),y)
-CFLAGS += $(call cc-option,-Os,$(call cc-option,-O2,))
+# CFLAGS += $(call cc-option,-Os,$(call cc-option,-O2,))
 else
 CFLAGS += $(call cc-option,-g,)
 #CFLAGS += "-D_FORTIFY_SOURCE=2"
